version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

#  web:
#    build: ./raspberrypi
#    ports:
#      - "5000:5000"
#    depends_on:
#      - mosquitto

  echo-service:
    build:
      context: ./echo-service
      dockerfile: ./docker/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mosquitto

#  angular:
#    build: ./angular
#    ports:
#      - "4200:4200"
#    depends_on:
#      - web